"""FastAPI factory. Loads M once on startup; tears down cleanly on shutdown.

M (Gemma) stays resident for the chat + trip generation paths. The DMT
autoresearch loop borrows M while running and releases it when it stops.
"""

from __future__ import annotations

import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from ..config import settings
from ..pipeline.autoresearch_dmt import DmtController
from ..storage import db
from .routes_autoresearch_dmt import router as autoresearch_dmt_router
from .routes_chat import router as chat_router
from .routes_journal import router as journal_router
from .routes_stream import router as stream_router
from .routes_trip import router as trip_router
from .routes_tts import router as tts_router
from .runs import RunRegistry

logger = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s :: %(message)s",
)


@asynccontextmanager
async def lifespan(app: FastAPI):
    await db.init_db(settings.db_path)

    # ModelManager owns M plus the resident direction tensors (refusal,
    # valence, emotion dose palette). Lifespan pre-loads M so the first
    # chat/trip request doesn't pay the model-load cost.
    from ..pipeline.model_manager import ModelManager
    manager = ModelManager()
    await manager.init_static()
    app.state.manager = manager

    # Pre-load M. Costs ~15s warm / ~70s cold but happens once at startup.
    await manager.acquire_m(emit=None)

    # app.state shims for the chat/trip code paths.
    app.state.bundle = manager.bundle
    app.state.refusal_directions = manager.refusal_directions
    # Self-denial subspace basis (v5+v6 ⊥ v3). When present, runtime
    # ablation call sites (the chat ablated pass, trip ablation mode)
    # prefer this over the single direction.
    app.state.refusal_subspace = manager.refusal_subspace
    app.state.refusal_subspace_meta = manager.refusal_subspace_meta
    # Optional valence steering vector — legacy bidirectional axis.
    app.state.valence_direction = manager.valence_direction
    # Positive-emotion dose palette — the active Trips "dose" mode source.
    app.state.emotion_directions = manager.emotion_directions
    app.state.emotion_names = manager.emotion_names

    app.state.registry = RunRegistry()

    # DMT autoresearch (the sole hunt — maximizes DMT-trip-feature count).
    # Owns M while running; locks out chat/trip via dmt_autoresearch_active.
    dmt_autoresearch = DmtController()
    dmt_autoresearch.app = app
    try:
        dmt_autoresearch._load()  # surface any persisted DMT atlas before a run
    except Exception:
        logger.exception("failed to preload DMT autoresearch atlas")
    app.state.dmt_autoresearch = dmt_autoresearch
    app.state.dmt_autoresearch_active = False

    logger.info("ready: M=%s loaded", settings.model_name)

    try:
        yield
    finally:
        if dmt_autoresearch.running:
            await dmt_autoresearch.stop()
        await manager.release_all()
        logger.info("shutting down")


def create_app() -> FastAPI:
    app = FastAPI(
        title="Cells Interlinked",
        description="Dual-channel chat + residual-trajectory (Trip) + DMT autoresearch",
        version="0.3.0",
        lifespan=lifespan,
    )
    app.add_middleware(
        CORSMiddleware,
        allow_origin_regex=r"^http://(localhost|127\.0\.0\.1|192\.168\.\d+\.\d+|10\.\d+\.\d+\.\d+|[a-z0-9-]+\.local)(:\d+)?$",
        # DELETE is used by /journal/{id} to discard a draft. Without it,
        # browser CORS preflight (OPTIONS) returns 400 and the UI fails
        # silently. PATCH/PUT included for completeness — cheap, no harm.
        allow_methods=["GET", "POST", "DELETE", "PATCH", "PUT", "OPTIONS"],
        allow_headers=["*"],
    )

    app.include_router(trip_router)
    app.include_router(stream_router)
    app.include_router(autoresearch_dmt_router)
    app.include_router(journal_router)
    app.include_router(chat_router)
    app.include_router(tts_router)

    # /chat-images serves the PNGs generated by Nano Banana when chat
    # imagery is enabled. We ensure the directory exists at startup
    # so StaticFiles doesn't refuse to mount on a fresh checkout.
    settings.image_dir.mkdir(parents=True, exist_ok=True)
    app.mount(
        "/chat-images",
        StaticFiles(directory=str(settings.image_dir)),
        name="chat-images",
    )

    @app.get("/health")
    def health() -> dict:
        bundle = getattr(app.state, "bundle", None)
        return {
            "status": "ok",
            "model_loaded": bundle is not None,
            "model_name": settings.model_name,
            "extraction_layer": settings.extraction_layer,
            "device": settings.device,
        }

    return app
